language: php
php:
    - 5.5
    - 5.4

before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - phpunit --coverage-clover coverage.clover test/Flash/FlashTest.php test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover